# Note: This crate must be built using do.sh

[package]
name = "serum-pool-simple"
version = "0.1.0"
description = "Simple serum pool"
edition = "2018"

[features]
no-entrypoint = []
skip-no-mangle = ["solana-sdk/skip-no-mangle"]
program = [
    "solana-sdk/program",
    "serum-pool/program"
]
default = [
    "solana-sdk/default",
]

[dependencies]
solana-sdk = { version = "1.3.9", default-features = false, optional = true }
serum-pool = { version = "0.1.0", path = "../..", default-features = false }

[lib]
name = "serum_pool_examples_simple"
crate-type = ["cdylib", "lib"]
